import os
import re
import json
import tempfile
from datetime import timedelta
from pathlib import Path
from asyncio import create_subprocess_exec
from asyncio.subprocess import PIPE

from bot import LOGGER, user_data

ASS_HEADER_TEMPLATE = """[Script Info]\n; Script generated by BLX Intro Subtitle Generator\nScriptType: v4.00+\nPlayResX: 1920\nPlayResY: 1080\nScaledBorderAndShadow: yes\nWrapStyle: 2\nYCbCr Matrix: TV.709\n\n[V4+ Styles]\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\nStyle: Intro,{font},{size},&H00FFFFFF,&H0000FFFF,&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,3,0,{align},60,60,{margin_v},1\n\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"""

# Alignment map: bottom=2, center=5, top=8 (ASS spec: 1-3 bottom, 4-6 mid, 7-9 top)
ALIGN_MAP = {"bottom": 2, "center": 5, "top": 8}

# Color name to hex mapping
COLOR_NAME_MAP = {
    "red": "#FF0000",
    "blue": "#0000FF",
    "green": "#00FF00",
    "yellow": "#FFFF00",
    "white": "#FFFFFF",
    "black": "#000000",
    "orange": "#FFA500",
    "purple": "#800080",
    "pink": "#FF69B4",
    "cyan": "#00FFFF",
    "magenta": "#FF00FF",
    "lime": "#32CD32",
    "gold": "#FFD700",
    "silver": "#C0C0C0",
    "brown": "#A52A2A",
    "gray": "#808080",
    "grey": "#808080",
    "violet": "#8A2BE2",
    "indigo": "#4B0082",
    "navy": "#000080",
    "teal": "#008080",
    "olive": "#808000",
    "maroon": "#800000",
    "aqua": "#00FFFF",
    "fuchsia": "#FF00FF",
    "coral": "#FF7F50",
    "salmon": "#FA8072",
    "crimson": "#DC143C",
    "darkred": "#8B0000",
    "darkblue": "#00008B",
    "darkgreen": "#006400",
    "lightblue": "#ADD8E6",
    "lightgreen": "#90EE90",
    "lightgray": "#D3D3D3",
    "lightgrey": "#D3D3D3",
}

DEFAULT_COLORS = ["#FF0000", "#0000FF", "#00FF00", "#FFA500", "#800080", "#000000"]

HEX_TO_ASS = lambda h: (
    f"&H00{h[5:7]}{h[3:5]}{h[1:3]}"
    if re.match(r"^#?[0-9A-Fa-f]{6}$", h)
    else "&H00FFFFFF"
)


def get_available_colors():
    """Return a list of available color names."""
    return list(COLOR_NAME_MAP.keys())


def get_color_examples():
    """Return formatted examples of color usage."""
    basic_colors = ["red", "blue", "green", "yellow", "white"]
    return f"Examples: {' | '.join(basic_colors)} or {' | '.join([COLOR_NAME_MAP[c] for c in basic_colors[:3]])}"


def validate_color_input(colors_raw):
    """Validate and return parsed colors from user input."""
    colors = []
    invalid_colors = []

    if colors_raw:
        sep = "|" if "|" in colors_raw else " "
        for c in colors_raw.split(sep):
            c = c.strip().lower()
            if not c:
                continue
            # Check if it's a color name first
            if c in COLOR_NAME_MAP:
                colors.append(COLOR_NAME_MAP[c])
            # Check if it's a hex color with #
            elif (
                c.startswith("#") and len(c) == 7 and re.match(r"^#[0-9A-Fa-f]{6}$", c)
            ):
                colors.append(c)
            # Check if it's a hex color without #
            elif re.match(r"^[0-9A-Fa-f]{6}$", c):
                colors.append("#" + c)
            else:
                invalid_colors.append(c)

    return colors, invalid_colors


def _format_ass_time(ms: int) -> str:
    td = timedelta(milliseconds=ms)
    total_seconds = int(td.total_seconds())
    h = total_seconds // 3600
    m = (total_seconds % 3600) // 60
    s = total_seconds % 60
    cs = int((td.microseconds / 1e6 + td.seconds - total_seconds) * 100)  # centiseconds
    return f"{h}:{m:02d}:{s:02d}.{cs:02d}"


async def generate_intro_ass(user_id: int, video_path: str) -> Path | None:
    user_dict = user_data.get(user_id, {})

    # Debug: Log user settings
    LOGGER.info(f"Intro subtitle settings for user {user_id}:")
    LOGGER.info(f"  ENABLED: {user_dict.get('INTRO_SUBTITLE_ENABLED', False)}")
    LOGGER.info(f"  TEXT: '{user_dict.get('INTRO_SUBTITLE_TEXT', 'Not set')}'")
    LOGGER.info(f"  STYLE: '{user_dict.get('INTRO_SUBTITLE_STYLE', 'Not set')}'")
    LOGGER.info(f"  COLORS: '{user_dict.get('INTRO_SUBTITLE_COLORS', 'Not set')}'")

    if not user_dict.get("INTRO_SUBTITLE_ENABLED", False):
        LOGGER.info(f"Intro subtitle disabled for user {user_id}")
        return None

    text = user_dict.get("INTRO_SUBTITLE_TEXT") or "Encoded by BLX"
    style = (user_dict.get("INTRO_SUBTITLE_STYLE") or "typing").lower()
    font_path = user_dict.get("INTRO_SUBTITLE_FONT_PATH") or ""
    font_size = int(user_dict.get("INTRO_SUBTITLE_FONT_SIZE") or 48)
    position = (user_dict.get("INTRO_SUBTITLE_POSITION") or "bottom").lower()
    colors_raw = user_dict.get("INTRO_SUBTITLE_COLORS") or ""
    per_char_ms = int(user_dict.get("INTRO_SUBTITLE_CHAR_MS") or 300)

    # Parse colors
    colors, invalid_colors = validate_color_input(colors_raw)
    if not colors:
        colors = DEFAULT_COLORS

    # Debug logging
    LOGGER.info(
        f"Intro subtitle colors for user {user_id}: input='{colors_raw}', parsed={colors}"
    )
    if invalid_colors:
        LOGGER.warning(f"Invalid colors ignored: {invalid_colors}")

    align = ALIGN_MAP.get(position, 2)
    margin_v = 80 if position == "bottom" else 60

    # Build events
    events = []
    total_ms = 0

    if style == "typing":
        # per-character progressive line using karaoke timing \k
        syllables = []
        for i, ch in enumerate(text):
            duration_cs = max(1, per_char_ms // 10)
            colour = colors[i % len(colors)]
            ass_color = HEX_TO_ASS(colour)
            # Simple approach: color then karaoke timing
            syllables.append(f"{{\\k{duration_cs}}}{{\\c{ass_color}}}{ch}")
            total_ms += per_char_ms
        # Fallback total duration
        end_ms = total_ms + 500
        line = "".join(syllables)
        events.append(
            f"Dialogue: 0,{_format_ass_time(0)},{_format_ass_time(end_ms)},Intro,,0,0,0,,{{\\fad(200,300)}}{line}"
        )
    elif style == "fade":
        # Apply first color for fade style
        first_color = colors[0] if colors else DEFAULT_COLORS[0]
        ass_color = HEX_TO_ASS(first_color)
        duration_ms = max(2000, per_char_ms * len(text))
        events.append(
            f"Dialogue: 0,{_format_ass_time(0)},{_format_ass_time(duration_ms)},Intro,,0,0,0,,{{\\fad(300,500)\\c{ass_color}}}{text}"
        )
    else:  # static
        # Apply first color for static style
        first_color = colors[0] if colors else DEFAULT_COLORS[0]
        ass_color = HEX_TO_ASS(first_color)
        duration_ms = max(1500, per_char_ms * min(len(text), 5))
        events.append(
            f"Dialogue: 0,{_format_ass_time(0)},{_format_ass_time(duration_ms)},Intro,,0,0,0,,{{\\c{ass_color}}}{text}"
        )

    ass_content = (
        ASS_HEADER_TEMPLATE.format(
            font=os.path.basename(font_path) if font_path else "Arial",
            size=font_size,
            align=align,
            margin_v=margin_v,
        )
        + "\n".join(events)
        + "\n"
    )

    tmp_dir = Path(video_path).parent
    ass_path = tmp_dir / "intro_generated.ass"
    try:
        ass_path.write_text(ass_content, encoding="utf-8")
        LOGGER.info(f"Generated intro ASS at {ass_path}")
        return ass_path
    except Exception as e:
        LOGGER.error(f"Failed writing intro ASS: {e}")
        return None


async def mux_intro_subtitle(
    video_path: str, ass_path: Path, user_id: int
) -> str | None:
    """Mux the ASS as default soft subtitle without re-encoding. Attach font if provided."""
    user_dict = user_data.get(user_id, {})
    font_path = user_dict.get("INTRO_SUBTITLE_FONT_PATH") or ""

    # Output: change container to mkv to support font attachments
    p = Path(video_path)
    out_path = (
        str(p.with_suffix(".mkv"))
        if p.suffix.lower() != ".mkv"
        else str(p.parent / f"{p.stem}_intro.mkv")
    )
    # Count existing subtitle streams to target correct disposition index
    existing_subs = 0
    try:
        probe_cmd = [
            "ffprobe",
            "-v",
            "error",
            "-select_streams",
            "s",
            "-show_entries",
            "stream=index",
            "-of",
            "csv=p=0",
            video_path,
        ]
        proc = await create_subprocess_exec(*probe_cmd, stdout=PIPE, stderr=PIPE)
        stdout, _ = await proc.communicate()
        if proc.returncode == 0:
            # Each line corresponds to a subtitle stream index (original stream index, not contiguous per type). We just count lines.
            existing_subs = len(
                [l for l in stdout.decode().strip().splitlines() if l.strip() != ""]
            )
    except Exception as e:
        LOGGER.warning(f"Failed to count existing subtitle streams: {e}")

    # New intro subtitle will be appended after mapping original streams; its subtitle type index will equal existing_subs
    intro_sub_index = existing_subs

    # Build command (keep all original streams, append new ASS, mark it default)
    cmd = [
        "ffmpeg",
        "-hide_banner",
        "-loglevel",
        "error",
        "-i",
        video_path,
        "-i",
        str(ass_path),
        "-map",
        "0",
        "-map",
        "1:0",
        "-c",
        "copy",
        "-c:s",
        "ass",
        f"-disposition:s:{intro_sub_index}",
        "default",
    ]
    if font_path and os.path.exists(font_path):
        cmd += [
            "-attach",
            font_path,
            "-metadata:s:t:0",
            "mimetype=application/x-truetype-font",
            "-metadata:s:t:0",
            f"filename={os.path.basename(font_path)}",
        ]
    cmd += [out_path]

    LOGGER.info(
        f"Muxing intro subtitle (existing subs={existing_subs}, new index={intro_sub_index}): {' '.join(cmd)}"
    )
    proc = await create_subprocess_exec(*cmd, stdout=PIPE, stderr=PIPE)
    _, stderr = await proc.communicate()
    if proc.returncode != 0:
        LOGGER.error(f"Intro subtitle mux failed: {stderr.decode(errors='ignore')}")
        return None
    # Ensure output exists
    if not os.path.exists(out_path):
        LOGGER.error("Mux output missing")
        return None
    return out_path


def test_color_generation(colors_input: str, text: str = "Test Colors") -> str:
    """Generate a test ASS content to verify color application."""
    colors, invalid_colors = validate_color_input(colors_input)
    if not colors:
        colors = DEFAULT_COLORS

    # Simple test generation - just show colors without karaoke
    syllables = []
    for i, ch in enumerate(text):
        if ch == " ":
            syllables.append(" ")
            continue
        colour = colors[i % len(colors)]
        ass_color = HEX_TO_ASS(colour)
        syllables.append(f"{{\\c{ass_color}}}{ch}")

    line = "".join(syllables)

    # Create a simple test ASS file content
    ass_header = ASS_HEADER_TEMPLATE.format(font="Arial", size=48, align=2, margin_v=80)

    # Add both static and typing test lines
    test_events = [
        f"Dialogue: 0,0:00:00.00,0:00:03.00,Intro,,0,0,0,,{{\\c{HEX_TO_ASS(colors[0])}}}Static: {text}",
        f"Dialogue: 0,0:00:04.00,0:00:08.00,Intro,,0,0,0,,Multi-color: {line}",
    ]

    ass_content = ass_header + "\n".join(test_events) + "\n"

    result = f"Input: '{colors_input}'\n"
    result += f"Colors parsed: {colors}\n"
    if invalid_colors:
        result += f"Invalid colors ignored: {invalid_colors}\n"
    result += f"\nGenerated test ASS content:\n{ass_content}"

    return result


def diagnose_intro_subtitle_settings(user_id: int) -> str:
    """Diagnose intro subtitle settings for a user"""
    from bot import user_data

    user_dict = user_data.get(user_id, {})

    diagnosis = f"🔍 **Intro Subtitle Diagnosis for User {user_id}**\n\n"

    # Check if feature is enabled
    enabled = user_dict.get("INTRO_SUBTITLE_ENABLED", False)
    diagnosis += f"✅ **Enabled**: {enabled}\n"
    if not enabled:
        diagnosis += "❌ **Issue**: Intro subtitle is not enabled. Enable it in settings first.\n"
        return diagnosis

    # Check text
    text = user_dict.get("INTRO_SUBTITLE_TEXT", "")
    diagnosis += f"📝 **Text**: '{text or 'Default: Encoded by BLX'}'\n"

    # Check style
    style = user_dict.get("INTRO_SUBTITLE_STYLE", "")
    diagnosis += f"🎨 **Style**: '{style or 'Default: typing'}'\n"

    # Check colors
    colors_raw = user_dict.get("INTRO_SUBTITLE_COLORS", "")
    diagnosis += f"🌈 **Colors Input**: '{colors_raw or 'Not set - using defaults'}'\n"

    if colors_raw:
        colors, invalid = validate_color_input(colors_raw)
        diagnosis += f"✅ **Valid Colors**: {colors}\n"
        if invalid:
            diagnosis += f"❌ **Invalid Colors**: {invalid}\n"
    else:
        diagnosis += f"📋 **Default Colors**: {DEFAULT_COLORS}\n"

    # Check other settings
    font_size = user_dict.get("INTRO_SUBTITLE_FONT_SIZE", "")
    position = user_dict.get("INTRO_SUBTITLE_POSITION", "")
    char_ms = user_dict.get("INTRO_SUBTITLE_CHAR_MS", "")

    diagnosis += f"📏 **Font Size**: {font_size or 'Default: 48'}\n"
    diagnosis += f"📍 **Position**: {position or 'Default: bottom'}\n"
    diagnosis += f"⏱️ **Char Timing**: {char_ms or 'Default: 300ms'}\n"

    # Provide recommendations
    diagnosis += "\n🔧 **Recommendations**:\n"
    if not colors_raw:
        diagnosis += (
            "• Set custom colors: `red|blue|green` or `#FF0000|#00FF00|#0000FF`\n"
        )
    if style.lower() not in ["typing", "fade", "static"]:
        diagnosis += "• Use valid style: typing, fade, or static\n"

    return diagnosis


async def apply_intro_subtitle(video_path: str, user_id: int) -> str:
    """High-level helper: generate ASS then mux. Return new path or original."""
    try:
        ass_path = await generate_intro_ass(user_id, video_path)
        if not ass_path:
            return video_path
        new_path = await mux_intro_subtitle(video_path, ass_path, user_id)
        # Remove generated ASS file so it isn't uploaded/listed
        try:
            if ass_path and ass_path.exists():
                ass_path.unlink()
        except Exception as e:
            LOGGER.debug(f"Could not remove temp intro ASS file: {e}")
        if (
            new_path
            and user_data.get(user_id, {}).get("KEEP_MERGE_SOURCE_FILES", False)
            is False
        ):
            try:
                if (
                    os.path.exists(new_path)
                    and os.path.exists(video_path)
                    and new_path != video_path
                ):
                    os.remove(video_path)
            except Exception as e:
                LOGGER.warning(f"Could not remove original video after intro mux: {e}")
        return new_path or video_path
    except Exception as e:
        LOGGER.error(f"apply_intro_subtitle error: {e}")
        return video_path
